### PR TITLE
fix #25

### LINKED ISSUE #25: HorizontalHelpWidget misalignments
firefox 104.0.1 (64-bit) @ mbp m1 13
renderer: html

main view: wrong text spacing leads to overflow
image

options view: looks about right
image

collapsed: perfect
image

Safari 15.6.1 @ mbp m1 13
renderer: html

collapsed: perfect
image

main: literally everything is mismatched (cross is normally in center but sometimes it is like on screenshot)
image

options: wrong spacing between column items, heart icon too small
image

### PR DESCRIPTION
**Pull request by dazzlemon**

### CODE REVIEW

**Comment by solid-danylosafonov** [comment]
main view on firefox 104.0.1
image

**Comment by solid-danylosafonov** [comment]
options view looks good on firefox too
image

**Comment by solid-danylosafonov** [comment]
so does collapsed
image

**Comment by solid-danylosafonov** [comment]
safari

collapsed: just a bit smaller (is there a way to do anything without breaking it on firefox?)
image

main: not close at all
image

options: wrong card size, letter spacing, heart icon size, divider spacing
image

**Comment by solid-danylosafonov** [comment]
image

**Comment by solid-danylosafonov** [comment]
collapsed view is good too, because no text
image

**Comment by solid-danylosafonov** [comment]
icons on the original site fallback to sans-serif, but otherwise it's close
image

**Review by solid-yuriiprykhodko — APPROVED** [review]
LGTM!

**Pull request merged**
