### PR TITLE
Adjust for pixel-perfection

### PR DESCRIPTION
**Pull request by solid-yuriiprykhodko**
image

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Great job @solid-yuriiprykhodko! Please resolve conflict issues and slightly change dialog size and flag positioning to make it pixel perfect. Great to see changes with font sizes.

**Comment by solid-danylokhvan** [comment]
Снимок экрана 2022-09-12 в 21 09 41

**Comment by solid-danylokhvan** [comment]
Снимок экрана 2022-09-12 в 22 52 47

**Comment by solid-software** [comment]
@solid-danylokhvan please solve all the conflicts:
image

**Comment by solid-danylokhvan** [comment]
Снимок экрана 2022-09-13 в 12 46 58

**Comment by solid-danylokhvan** [comment]
wothLetterSpacing

**Comment by solid-yuriiprykhodko** [comment]
@solid-danylokhvan The changes have affected the second widget variant.

Second widget on `master` (6b01666):

image

Second widget on `widget1-pixelperfect` (8806cca):

image

**Comment by solid-danylokhvan** [comment]
Снимок экрана 2022-09-13 в 18 59 36
Снимок экрана 2022-09-13 в 19 09 21

**Comment by solid-danylokhvan** [comment]
> @solid-danylokhvan The changes have affected the second widget variant.
> 
> Second widget on `master` ([6b01666](https://github.com/solid-software/help_ukraine_widget/commit/6b01666c8844b5153ebe0636a70cb3627cc41332)):
> 
> image
> 
> Second widget on `widget1-pixelperfect` ([8806cca](https://github.com/solid-software/help_ukraine_widget/commit/8806cca90a1f29f826539ae2822943032b9f1ba1)):
> 
> image

Completed

**Review by ghost — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
