### PR TITLE
rename_help_widget_on_help_ukraine_widget

### LINKED ISSUE #34: Rename HelpWidget -> HelpUkraineWidget
This should give the name that is matching package name and more closer to what widget does.

### PR DESCRIPTION
**Pull request by solid-danylokhvan**
I've renamed widget from HelpWidget to HelpUkraineWidget and enum from HelpWidgetView to HelpUkraineWidgetView and renamed files for it.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
LGTM - thanks!

**Comment by solid-software** [comment]
@solid-danylokhvan please resolve conflicts and let me know that it's done, Thanks!

**Review by solid-yuriiprykhodko — APPROVED** [review]
LGTM!

**Review by illia-romanenko — APPROVED** [review]
LGTM

**Pull request merged**
